# Generated by Django 3.1.7 on 2021-03-20 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_claim_claimtopic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='claimer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to=settings.AUTH_USER_MODEL),
        ),
    ]
