# Generated by Django 3.1.7 on 2021-03-20 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_claim_answer_date_expiration'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='answer_date_expiration',
            field=models.DateTimeField(null=True),
        ),
    ]
