# Generated by Django 3.2 on 2021-05-04 18:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_customuser_friendship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='friendship',
            field=models.ManyToManyField(blank=True, related_name='_users_customuser_friendship_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
