# Generated by Django 3.2 on 2021-05-06 06:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_customuser_friendship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='friendship',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
