# Generated by Django 3.2 on 2021-05-09 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_customuser_friendship'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendshipRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания запроса')),
                ('message', models.CharField(blank=True, max_length=100, null=True, verbose_name='Сообщение к запросу на добавление в друзья')),
                ('is_rejected', models.BooleanField(blank=True, null=True, verbose_name='Отклоненный запрос')),
                ('is_accepted', models.BooleanField(blank=True, null=True, verbose_name='Принятый запрос')),
                ('from_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendship_request_sent', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель запроса')),
                ('to_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendship_request_received', to=settings.AUTH_USER_MODEL, verbose_name='Получатель запроса')),
            ],
            options={
                'verbose_name': 'Friendship Request',
                'verbose_name_plural': 'Friendship Requests',
            },
        ),
    ]
