# Generated by Django 3.2 on 2021-05-09 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_friendshiprequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendshiprequest',
            old_name='from_user_id',
            new_name='from_user',
        ),
        migrations.RenameField(
            model_name='friendshiprequest',
            old_name='to_user_id',
            new_name='to_user',
        ),
        migrations.AlterUniqueTogether(
            name='friendshiprequest',
            unique_together={('from_user', 'to_user')},
        ),
    ]
