# Generated by Django 3.2 on 2021-05-09 14:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20210509_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='friendship',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Друзья'),
        ),
    ]
