# Generated by Django 3.2 on 2021-05-10 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_customuser_friendship'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='friendshiprequest',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('is_rejected', True), ('is_accepted', False)), models.Q(('is_rejected', False), ('is_accepted', True)), _connector='OR'), name='status_check'),
        ),
    ]
