# Generated by Django 3.2 on 2021-05-11 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_friendshiprequest_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendshiprequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата ответа запроса'),
        ),
    ]
