# Generated by Django 3.2 on 2021-05-16 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_friendshiprequest_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friendshiprequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Friendship Request', 'verbose_name_plural': 'Friendship Requests'},
        ),
    ]
