# Generated by Django 3.2 on 2021-06-01 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_friendshiprequest_updated_at'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['username'], name='users_custo_usernam_a8ad03_idx'),
        ),
    ]
