# Generated by Django 3.2 on 2021-05-27 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=32)),
                ('is_stats_deliver_ordered', models.BooleanField(default=False, verbose_name='Is stats message needed')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date of add bot to chat')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date of update')),
            ],
        ),
    ]
