# Generated by Django 3.1.7 on 2021-03-03 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Game name')),
            ],
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('game', models.ForeignKey(default='default_game', on_delete=django.db.models.deletion.CASCADE, to='games.games', to_field='name')),
            ],
        ),
        migrations.CreateModel(
            name='GameScores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name='score')),
                ('game_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_session', to='games.gamesession')),
            ],
        ),
    ]
