# Generated by Django 3.1.7 on 2021-03-15 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_gamescores_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamesession',
            options={'ordering': ['-created_at']},
        ),
    ]
