# Generated by Django 3.1.7 on 2021-03-22 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_auto_20210316_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='game_cover_art',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
