# Generated by Django 3.1.7 on 2021-03-22 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_games_game_cover_art'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='games',
            name='game_cover_art',
        ),
    ]
