# Generated by Django 3.1.7 on 2021-03-22 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_remove_games_game_cover_art'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='cover_art',
            field=models.ImageField(null=True, upload_to='uploads/games_cover/%Y/%m/%d/'),
        ),
    ]
