# Generated by Django 3.1.7 on 2021-04-01 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_games_cover_art'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='cover_art',
            field=models.ImageField(max_length=120, null=True, upload_to='uploads/games_cover/%Y/%m/%d/'),
        ),
    ]
