# Generated by Django 3.1.7 on 2021-04-02 15:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0011_auto_20210401_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='cover_art',
            field=models.ImageField(default='None', max_length=120, upload_to='uploads/games_cover/%Y/%m/%d/', validators=[django.core.validators.validate_image_file_extension]),
        ),
    ]
